name: Build and Package VS Code Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js on Windows
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies on Windows
        run: npm install

      - name: Install vsce on Windows
        run: npm install @vscode/vsce

      - name: Build and package extension on Windows
        run: vsce package

      - name: Upload VSIX artifact from Windows
        uses: actions/upload-artifact@v3
        with:
          name: vscabbage-extension-windows
          path: '*.vsix'

  build_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js on macOS
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies on macOS
        run: npm install

      - name: Build and package extension on macOS
        run: vsce package

      - name: Upload VSIX artifact from macOS
        uses: actions/upload-artifact@v3
        with:
          name: vscabbage-extension-macos
          path: '*.vsix'
