name: Build and Package Extensions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout source code for cabbage3
        uses: actions/checkout@v2
        with:
          repository: rorywalsh/cabbage3
          path: cabbage3
          ref: develop
          fetch-depth: 1
          submodules: true

      - name: Verify cabbage3 directory
        run: |
          ls -l
          ls -l cabbage3

      - name: Set Up Signing Certificate  
        uses: apple-actions/import-codesign-certs@v3
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATE_P12 }}
          p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Download CsoundLib64 Package
        run: |
          curl -L -o CsoundLib64-7.0-vanilla-universal.pkg "https://www.dropbox.com/scl/fi/8afz58gvjvwsa0u0nwr9g/CsoundLib64-7.0-vanilla-universal.pkg?rlkey=6kw4upth3olvmymhfjsndwgt9&st=mcxkg1hx&dl=1"
          ls -l CsoundLib64-7.0-vanilla-universal.pkg
          chmod +x CsoundLib64-7.0-vanilla-universal.pkg
          sudo installer -pkg CsoundLib64-7.0-vanilla-universal.pkg -target /

      - name: Configure build for cabbage3
        run: |
          cd cabbage3
          cmake -GXcode -B build -S . -DCMAKE_OSX_DEPLOYMENT_TARGET="10.15"

      - name: Build macOS app for cabbage3
        run: |
          cd cabbage3
          cmake --build build --config Debug

      - name: Sign binaries
        env:
          APPLE_DEVELOPER_TEAM_ID: ${{ secrets.APPLE_DEVELOPER_TEAM_ID }}
        run: |
          cd cabbage3/build
          codesign --force -s "${APPLE_DEVELOPER_TEAM_ID}" -v CabbageAUv2Effect/out/CabbageAUv2Effect.component --deep --strict --options=runtime --timestamp

      # Checkout source code for vscabbage before copying the files
      - name: Checkout source code for vscabbage
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      # Copy Cabbage build directory files into vscabbage/src
      - name: Copy CabbageApp to vscabbage src directory
        run: |
          pwd
          mkdir -p ./src/CabbageBundle
          ls
          cd ..
          pwd
          ls
          cd ../cabbage3/build  # We need to go back to the cabbage3/build directory, which is outside vscabbage
          cp -r CabbageAUv2Effect/out/CabbageAUv2Effect.component ./src/CabbageBundle/CabbageAUv2Effect.component
          cp -r CabbageAUv2Synth/out/CabbageAUv2Synth.component ./src/CabbageBundle/CabbageAUv2Synth.component
          cp -r CabbageApp/out/CabbageApp.app ./src/CabbageBundle/CabbageApp.app
          cp -r CabbageStandaloneApp/out/CabbageStandaloneApp.app ./src/CabbageBundle/CabbageStandaloneApp.app
          cp -r CabbageVST3Effect/out/CabbageVST3Effect.vst3 ./src/CabbageBundle/CabbageVST3Effect.vst3
          cp -r CabbageStandaloneApp/out/CabbageStandaloneApp.app ./src/CabbageBundle/CabbageStandaloneApp.app


      - name: Set up Node.js (v18) on macOS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies on macOS
        run: npm install

      - name: Install vsce on macOS
        run: npm install -g @vscode/vsce

      - name: Build and package extension on macOS
        run: vsce package

      - name: Upload VSIX artifact from macOS
        uses: actions/upload-artifact@v3
        with:
          name: vscabbage-extension-macos
          path: '*.vsix'

  # build_windows:
  #   runs-on: windows-latest

  #   steps:
  #     - name: Checkout source code for vscabbage
  #       uses: actions/checkout@v1
  #       with:
  #         fetch-depth: 1
  #         submodules: true

  #     - name: Set Up Signing Certificate
  #       env:
  #         CERTIFICATE_P12: ${{ secrets.CERTIFICATE_P12 }}
  #         CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
  #       run: |
  #         echo "$CERTIFICATE_P12" | base64 --decode > certificate.p12
  #         security import certificate.p12 -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign

  #     - name: Set up Node.js (v18) on Windows
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Install dependencies on Windows
  #       run: npm install

  #     - name: Install vsce on Windows
  #       run: npm install -g @vscode/vsce

  #     - name: Build and package extension on Windows
  #       run: vsce package

  #     - name: Upload VSIX artifact from Windows
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: vscabbage-extension-windows
  #         path: '*.vsix'
